namespace Blockcoli.Libra.Net.Constant
{
    public static class ProgamBase64Codes
    {
        public static string PeerToPeerTxn => "TElCUkFWTQoBAAcBSgAAAAQAAAADTgAAAAYAAAANVAAAAAYAAAAOWgAAAAYAAAAFYAAAACkAAAAEiQAAACAAAAAIqQAAAA8AAAAAAAABAAIAAQMAAgACBAIAAwIEAgMABjxTRUxGPgxMaWJyYUFjY291bnQEbWFpbg9wYXlfZnJvbV9zZW5kZXIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAIABAAMAAwBEwEBAg==";    
    }
}